### ISSUE TITLE
realpath command not found

### ISSUE THREAD

**Issue by micahjon** [rayrutjes/wp-plugin-git-svn-sync#8]
Hi, 

First of all, thanks for a super helpful script. I tried running it on my MacBook Pro and got the following error messages:
```
./sync.sh: line 31: realpath: command not found
./sync.sh: line 33: realpath: command not found
````

Turns out I just had to define `realpath`, and then things worked fine. I got a suitable replacement from StackOverflow:
https://stackoverflow.com/a/3572105/1546808

```
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
```

**Comment by rayrutjes** [comment]
Hey @pranksinatra I opened a PR [here](#9).
Let me know what you think.
I wasn't convinced by any other realpath/readlink fallback so I just removed the usage.
